# Introduction to Numpy

NumPy (Numerical Python) is a fundamental library in Python for numerical and scientific computing.
It provides support for arrays, matrices, and a wide range of mathematical functions to work efficiently with large datasets and perform various mathematical operations

# Creating NumPy Array

### From List to Tuples

In [ ]:
import numpy as np
import pandas as pd

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Convert NumPy array to pandas DataFrame
df = pd.DataFrame(arr, columns=['Column_Name'])

# Print the DataFrame
print(df)


### Using Built-in Functions

### Creates a 3x3 array filled with zeros

In [ ]:
import numpy as np
import pandas as pd

# Create a NumPy array filled with zeros
zeros_arr = np.zeros((3, 3))

# Convert NumPy array to pandas DataFrame
df = pd.DataFrame(zeros_arr)

# Print the DataFrame
print(df)


### Creates a 2x2 array filled with ones

In [ ]:
import numpy as np
import pandas as pd

# Create a NumPy array filled with ones
ones_arr = np.ones((2, 2))

# Convert NumPy array to pandas DataFrame
df = pd.DataFrame(ones_arr)

# Print the DataFrame
print(df)


In [ ]:
pip install numpy

In [1]:
import numpy as np

In [4]:
np.sqrt(25)

np.float64(5.0)

### np.arange() and np.linspace() are NumPy functions used to create arrays with a sequence of numbers.

### np.arange()

In [6]:
import numpy as np

# Create array using arange
arr = np.arange(0, 11, 2)  # Creates an array [0, 2, 4, 6, 8]

# Print the array
print("Array from arange:")
print(arr)


Array from arange:
[ 0  2  4  6  8 10]


### np.linspace()

In [15]:
import numpy as np

# Create array using linspace
lin_arr = np.linspacepace(0, 10)  # Creates an array [0.  , 0.25, 0.5 , 0.75, 1.  ]

# Print the array
print("Array from linspace:")
print(lin_arr)


Array from linspace:
[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


### Random Arrays - Random arrays are arrays whose elements are generated randomly.

### Creates a 3x3 array with random values between 0 and 1

In [19]:
import numpy as np

# Create a 3x3 array with random values between 0 and 1
rand_arr = np.random.rand(3, 1)

# Print the random array
print(rand_arr)


[[0.39719037]
 [0.65653959]
 [0.76404099]]


### Using Dimension to generate N-dimensional arrays

In [22]:
import numpy as np

# Create a 2-dimensional array with specified dimensions
arr = np.array([1, 2, 3, 4], ndmin=2)

# Print the array
print(arr)

[[1 2 3 4]]


### The reshape() method in NumPy allows you to change the shape of an array

In [27]:
import numpy as np

# Create a 2-dimensional array with specified dimensions
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array to a 2x2 shape
reshaped_arr = arr.reshape((3, 2))

# Print the reshaped array
print(reshaped_arr)


[[1 2]
 [3 4]
 [5 6]]


###  You can check the type of the array object using the type() function in Python.

In [28]:
import numpy as np

# Create a 2-dimensional array with specified dimensions
arr = np.array([1, 2, 3, 4], ndmin=2)

# Print the type of the array object
print(type(arr))


<class 'numpy.ndarray'>


### You can use the shape attribute of a NumPy array to check its dimensions.

In [29]:
import numpy as np

# Create a 2-dimensional array with specified dimensions
arr = np.array([1, 2, 3, 4], ndmin=2)

# Print the shape of the array
print(arr.shape)


(1, 4)


### You can use the ndim attribute of a NumPy array to check its number of dimensions.

In [30]:
import numpy as np

# Create a 2-dimensional array with specified dimensions
arr = np.array([1, 2, 3, 4], ndmin=2)

# Print the number of dimensions of the array
print(arr.ndim)


2


### Data Types in NumPy

### Strings are sequences of characters, such as letters, numbers, symbols, or spaces, enclosed within single quotes (') or double quotes (").

In [31]:
import numpy as np

# Create a NumPy array of strings
str_arr = np.array(['ABC', 'DEF'], dtype=np.str_)

# Print the array
print("String array:", str_arr)


String array: ['ABC' 'DEF']


### Integers are whole numbers, positive or negative, without any decimal point.

In [ ]:
import numpy as np

# Create a NumPy array of integers
int_arr = np.array([1, 2, 3], dtype=np.int64)

# Print the array
print("Integer array:", int_arr)


### Floats (floating-point numbers) are numbers that have a decimal point or use exponential (scientific) notation. They can represent both integer and fractional parts of numbers.

In [ ]:
import numpy as np

# Create a NumPy array of floats
float_arr = np.array([5.98, 3.14], dtype=np.float64)

# Print the array
print("Float array:", float_arr)


### Booleans are a data type that represents one of two possible values: True or False.

In [32]:
import numpy as np

# Create a NumPy array of booleans
bool_arr = np.array([True, False, True], dtype=np.bool_)

# Print the array
print("Boolean array:", bool_arr)


Boolean array: [ True False  True]


### Complex numbers consist of a real part and an imaginary part, where the imaginary part is represented by the letter j or J.

In [ ]:
import numpy as np

# Create a NumPy array of complex numbers
complex_arr = np.array([1.0 + 2.0j, 3.0 + 4.0j], dtype=np.complex128)

# Print the array
print("Complex array:", complex_arr)


### Creating NumPy arrays with specific data types using the dtype parameter.

### Creating an array of integers without specifying the data type:

In [33]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)


int64


### Creating an array of strings with a specific data type ('S' for strings):

In [ ]:
arr = np.array(['dogs', 'cats', 'horses'], dtype='S')
print(arr.dtype)  # |S6


# Indexing and Slicing NumPy Arrays


### NumPy arrays can be accessed and sliced similar to Python lists, with the additional ability to index and slice in multiple dimensions for multi-dimensional arrays.


### Create a Numpy Array

In [34]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

### Accessing elements

In [35]:
element = arr[0, 1]  # Accessing the element at the first row and second column
print("Element at first row and second column:", element)

Element at first row and second column: 2


### Slicing Rows

In [36]:
slice_row = arr[1,:]  # Slicing the second row
print("Second row:", slice_row)

Second row: [4 5 6]


### Slicing Columns


In [37]:
slice_column = arr[:, 2]  # Slicing the third column
print("Third column:", slice_column)

Third column: [3 6 9]


### Advanced indexing with boolean masking

In [39]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
mask = arr > 5  # Creating a boolean mask for values greater than 5
filtered = arr[mask]  # Getting values greater than 5
print("Boolean mask for values greater than 5:\n", mask)
print("Values greater than 5:\n", filtered)

Boolean mask for values greater than 5:
 [[False False False]
 [False False  True]
 [ True  True  True]]
Values greater than 5:
 [6 7 8 9]


### Create the following rank 2 array with shape (3, 4)


In [42]:
import numpy as np

# Given NumPy array
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

# Print the array
print(a)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Use slicing to pull out the subarray consisting of the first 2 rows and columns 1 and 2; b is the following array of shape (2, 2):


In [44]:
a[:2, 1:3]

array([[2, 3],
       [6, 7]])

In [46]:
a[:2, :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [49]:
a[:2, 1:3]

array([[2, 3],
       [6, 7]])

In [43]:
import numpy as np

# Given NumPy array
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

# Slicing the array
b = a[:2, 1:3]

# Print the sliced array
print("Sliced array b:")
print(b)


Sliced array b:
[[2 3]
 [6 7]]


### A slice of an array is a view into the same data, so modifying it will modify the original array.


In [53]:
import numpy as np

# Given NumPy array
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

# Slicing the array
b = a[:2, 1:3]

# Print element of a
print("Element of a[0, 1]:", a[0, 1])   # Prints "2"

# Modify element of b
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]

# Print modified element of a
print("Modified element of a[0, 1]:", a[0, 1])   # Prints "77"


Element of a[0, 1]: 2
Modified element of a[0, 1]: 77


In [54]:
a

array([[ 1, 77,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [55]:
b

array([[77,  3],
       [ 6,  7]])

# Numpy Operations

### NumPy arrays support a wide range of operations, including arithmetic, statistical, and more. These operations are performed element-wise.


### Element-wise arithmetic operations - In element-wise operations, corresponding elements of the input structures are operated on together to produce an output structure of the same shape.


In [56]:
import numpy as np

# Given NumPy arrays
arr1 = np.array([1, 2, 3])  # Define the first NumPy array
arr2 = np.array([4, 5, 6])  # Define the second NumPy array



### Element-wise Addition:It refers to the process of adding corresponding elements of two arrays, matrices, or vectors together to produce a new array, matrix, or vector of the same shape.

In [57]:
addition = arr1 + arr2  # Perform element-wise addition
print("Element-wise addition:", addition)  # Print the result of addition


Element-wise addition: [5 7 9]


### Element-wise Subtraction:It is similar to element-wise addition, but instead of adding corresponding elements, it involves subtracting them.

In [58]:
subtraction = arr1 - arr2  # Perform element-wise subtraction
print("Element-wise subtraction:", subtraction)  # Print the result of subtraction


Element-wise subtraction: [-3 -3 -3]


### Element-wise Multiplication: It is a mathematical operation in which corresponding elements of two arrays, matrices, or vectors are multiplied together to produce a new array, matrix, or vector of the same shape.

In [59]:
multiplication = arr1 * arr2  # Perform element-wise multiplication
print("Element-wise multiplication:", multiplication)  # Print the result of multiplication


Element-wise multiplication: [ 4 10 18]


### Element-wise Division: It is a mathematical operation where corresponding elements of one array, matrix, or vector are divided by corresponding elements of another array, matrix, or vector, resulting in a new array, matrix, or vector of the same shape.

In [60]:
division = arr1 / arr2  # Perform element-wise division
print("Element-wise division:", division)  # Print the result of division


Element-wise division: [0.25 0.4  0.5 ]


### Statistical operations


### Statistical operations refer to various mathematical procedures used to analyze, interpret, summarize, and draw conclusions from data.

In [61]:
import numpy as np

# Given NumPy arrays
arr1 = np.array([1, 2, 3])  # Define the first NumPy array
arr2 = np.array([4, 5, 6])  # Define the second NumPy array

# Calculate mean and standard deviation
mean_arr1 = np.mean(arr1)  # Calculate the mean of arr1
std_dev_arr2 = np.std(arr2)  # Calculate the standard deviation of arr2

# Print results
print("Mean of arr1:", mean_arr1)  # Print the mean of arr1
print("Standard deviation of arr2:", std_dev_arr2)  # Print the standard deviation of arr2


Mean of arr1: 2.0
Standard deviation of arr2: 0.816496580927726


### Geometric Operations

### Exponentiation: Raises each element of the array to the power of Euler's number.

In [63]:
import numpy as np

arr1 = np.array([1, 2, 3])  # Define the input array
result_exp = np.exp(arr1)   # Compute element-wise exponentiation
print("Exponentiation of arr1:", result_exp)


Exponentiation of arr1: [ 2.71828183  7.3890561  20.08553692]


### Square Root: Computes the square root of each element in the array.

In [65]:
import numpy as np

arr1 = np.array([4, 9, 16])  # Define the input array
result_sqrt = np.sqrt(arr1)  # Compute element-wise square root
print("Square root of arr1:", result_sqrt)


Square root of arr1: [2. 3. 4.]


### Sine: Computes the sine of each element in the array treated as angles in radians.

In [64]:
import numpy as np

arr1 = np.array([0, np.pi/2, np.pi])  # Define the input array (angles in radians)
result_sin = np.sin(arr1)             # Compute element-wise sine
print("Sine of arr1:", result_sin)


Sine of arr1: [0.0000000e+00 1.0000000e+00 1.2246468e-16]


### Cosine: Computes the cosine of each element in the array treated as angles in radians.

In [ ]:
import numpy as np

arr1 = np.array([0, np.pi/2, np.pi])  # Define the input array (angles in radians)
result_cos = np.cos(arr1)             # Compute element-wise cosine
print("Cosine of arr1:", result_cos)


### Natural Logarithm: Computes the natural logarithm (base e) of each element in the array.

In [66]:
import numpy as np

arr1 = np.array([1, 2, 3])  # Define the input array
result_log = np.log(arr1)   # Compute element-wise natural logarithm
print("Natural logarithm of arr1:", result_log)


Natural logarithm of arr1: [0.         0.69314718 1.09861229]


### Aggregate Functions

### Sum: Computes the sum of all elements in the array.

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])  # Define the input array

# Sum of all elements in the array
sum_result = arr1.sum()
print("Sum of arr1:", sum_result)

### Minimum: Finds the minimum value among all elements in the array.

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])  # Define the input array

# Minimum value among all elements in the array
min_result = arr1.min()
print("Minimum value in arr1:", min_result)

### Maximum: Finds the maximum value among all elements in the array.

In [ ]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])  # Define the input array

# Maximum value among all elements in the array
max_result = arr1.max()
print("Maximum value in arr1:", max_result)

# Panda Series

### Pandas is a Python library for data manipulation and analysis, offering data structures like Series and DataFrame for handling structured data efficiently,

### creating a pandas series

In [ ]:
import pandas as pd

# Creating a Series from a list
data = [10, 20, 30, 40, 50]
series_from_list = pd.Series(data)


In [ ]:
import pandas as pd
import numpy as np

# Creating a Series from a NumPy array
numpy_array = np.array([1, 2, 3, 4, 5])
series_from_numpy = pd.Series(numpy_array)


In [ ]:
import pandas as pd

# Creating a Series with custom index labels
data = [10, 20, 30, 40, 50]
custom_index = pd.Series(data, index=['A', 'B', 'C', 'D', 'E'])


### Accessing elements by position (zero-based index)

This operation retrieves an element from a pandas Series based on its position, which follows a zero-based index (the first element has index 0, the second has index 1, and so on).

In [ ]:
# Example:
element_at_position_2 = series_from_list[2]
print("Element at position 2:", element_at_position_2)


### Accessing elements by label

 - This operation retrieves an element from a pandas Series based on its label.
 - When you create a Series with custom index labels, you can access elements using these labels.

In [ ]:
# Example:
element_with_label_B = custom_index['B']
print("Element with label 'B':", element_with_label_B)


### Slicing a series

Slicing allows you to select a subset of elements from a Series based on their positions.

In [ ]:
# Example:
slice_series = series_from_list[1:4]
print("Slice of series_from_list:", slice_series)


# Creating Pandas DataFrame

### Creating a DataFrame from a dictionary

In [ ]:
import pandas as pd

# Creating a DataFrame from a dictionary
data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 35]}
df_from_dict = pd.DataFrame(data)

# Print the DataFrame
print("DataFrame created from dictionary:")
print(df_from_dict)



### Creating a DataFrame from a list of lists with custom column names


In [ ]:
import pandas as pd

# Creating a DataFrame from a list of lists with custom column names
data_list = [['Alice', 25], ['Bob', 30], ['Charlie', 35]]
df_from_list = pd.DataFrame(data_list, columns=['Name', 'Age'])

# Print the DataFrame
print("DataFrame created from list of lists with custom column names:")
print(df_from_list)


### Creating a DataFrame from a CSV file


In [ ]:
import pandas as pd

# Creating a DataFrame from a CSV file
df_from_csv = pd.read_csv('data.csv')

# Print the DataFrame
print("DataFrame created from CSV file:")
print(df_from_csv)


### Creating an empty DataFrame


In [ ]:
import pandas as pd

# Creating an empty DataFrame
empty_df = pd.DataFrame()

# Print the empty DataFrame
print("Empty DataFrame:")
print(empty_df)


# Indexing a Pandas DataFrame

### DataFrames allow for various methods of indexing, including selecting columns, filtering rows, and more.


### Selecting a single column


In [ ]:
# Selecting a single column
name_column = df_from_dict['Name']
print(name_column)


###  Selecting multiple columns


In [ ]:
# Selecting multiple columns
subset = df_from_dict[['Name', 'Age']]
print(subset)


### Filtering Rows based on a condition

In [ ]:
# Filtering rows based on a condition
young_people = df_from_dict[df_from_dict['Age'] < 30]
print(young_people)


### Accessing a specific cell by row and column label


In [ ]:
# Accessing a specific cell by row and column label
cell_value = df_from_dict.at[0, 'Name']
print("Value at cell (row 0, column 'Name'):", cell_value)



# Loading Data from files


### SQL Databases - You can connect to SQL databases and retrieve data using Pandas.


In [ ]:
from sqlalchemy import create_engine

In [ ]:
# Create a database connection
engine = create_engine('sqlite:///database.db')

In [ ]:
data_from_sql = pd.read_sql_query('SELECT * FROM tracks', engine)

In [ ]:
data_from_sql

### Jason Files - JSON (JavaScript Object Notation) files are commonly used for semi-structured data.

In [ ]:
import pandas as pd

# Reading data from a JSON file with specified encoding
data_from_json = pd.read_json('data.json')

# Print the DataFrame
print("DataFrame created from JSON file:")
data_from_json

### HTML/Web Scraping: You can aslo Scrape data from HTML tables on webpages

In [ ]:
import pandas as pd

# Reading tables from a webpage
data_from_html = pd.read_html('https://www.w3schools.com/html/html_tables.asp')[0]  # Adjust index as needed
print("Data scraped from HTML table:")
data_from_html
